### ISSUE TITLE
Support multiple interfaces

### ISSUE THREAD

**Issue by tlnd** [travelping/docker-pcap#2]
Capturing multiple interfaces should be supported, i.e. a list of interfaces is passed as config in environment and each of the interfaces is captured.

Two options:
a) One capture file per interface
b) One capture file with traffic of all interfaces

Replacing `tcpdump` with `dumpcap` might be helpful.

**Comment by wfailla** [comment]
Is addressed in v0.3 (9c024cd23be9dc3c3b618a89ef4d0df2e5d6ab82) by changing to tshark.
